#! /bin/sh

## auto-start ##
feh --bg-fill ~/.wallpapers/t480.png --no-fehbg
wmname LG3D
sxhkd &
picom 2>~/.cache/.picom.err > ~/.cache/.picom.out &
dunst &
$HOME/.config/polybar/launch.sh
killall redshift; sleep 5; redshift &

## Monitors ##
bspc monitor eDP-1 -d I II III
bspc monitor DP-1 -d IV V VI VII VIII
bspc monitor DP-1-8 -d IV V VI VII VIII IX

## WM Config ##
bspc config border_width                3
bspc config window_gap                  15
bspc config bottom_padding              30
bspc config split_ratio                 0.55

bspc config normal_border_color         "#2e3440"
bspc config active_border_color         "#2e3440"
bspc config focused_border_color        "#151a23"

bspc config remove_unplugged_monitors   true
bspc config remove_disabled_monitors    true
bspc config focus_follows_pointer       true
bspc config borderless_monocle          true
bspc config gapless_monocle             true

## Special windows ##
bspc rule -a Zathura state=tiled
bspc rule -a pomotroid state=tiled