#! /bin/sh

## auto-start ##
feh --bg-fill ~/.wallpapers/t480.png --no-fehbg
$HOME/.config/polybar/launch.sh
wmname LG3D

sxhkd &
picom &
dunst &
killall redshift; sleep 5; redshift &

## Monitors ##
bspc monitor eDP-1 -d I II III
bspc monitor DP-1 -d IV V VI VII VIII
bspc monitor DP-1-8 -d IV V VI VII VIII IX

## WM Config ##
bspc config border_width         3
bspc config window_gap          10
bspc config bottom_padding      30

bspc config split_ratio          0.50

bspc config borderless_monocle   true
bspc config gapless_monocle      true

## Special windows ##
bspc rule -a Zathura state=tiled
bspc rule -a pavucontrol state=floating  # not working
bspc rule -a pomotroid state=tiled

